### ISSUE TITLE
ValueError: The following `model_kwargs` are not used by the model: ['images_or_videos', 'modal_list'] 

### ISSUE THREAD

**Issue by CaffeyChen** [DAMO-NLP-SG/VideoLLaMA2#90]
Hi teams,
I'm trying to build VideoLLaMa2 on my own server, but when I want to try Multi-model Version it comes "ValueError: The following `model_kwargs` are not used by the model: ['images_or_videos', 'modal_list'] ".

```
2024-09-12 16:42:59 | INFO | stdout | Load image...
2024-09-12 16:42:59 | INFO | stdout | Image: torch.Size([1, 3, 336, 336])
2024-09-12 16:42:59 | INFO | stdout | image_args: {'images_or_videos': tensor([[[[-0.0113, -0.0113, -0.0113,  ..., -0.0113, -0.0113, -0.0113],
2024-09-12 16:42:59 | INFO | stdout |           [-0.0113, -0.0113, -0.0113,  ..., -0.0113, -0.0113, -0.0113],
2024-09-12 16:42:59 | INFO | stdout |           [-0.0113, -0.0113, -0.0113,  ..., -0.0113, -0.0113, -0.0113],
2024-09-12 16:42:59 | INFO | stdout |           ...,
2024-09-12 16:42:59 | INFO | stdout |           [-0.0113, -0.0113, -0.0113,  ..., -0.0113, -0.0113, -0.0113],
2024-09-12 16:42:59 | INFO | stdout |           [-0.0113, -0.0113, -0.0113,  ..., -0.0113, -0.0113, -0.0113],
2024-09-12 16:42:59 | INFO | stdout |           [-0.0113, -0.0113, -0.0113,  ..., -0.0113, -0.0113, -0.0113]],
2024-09-12 16:42:59 | INFO | stdout |
2024-09-12 16:42:59 | INFO | stdout |          [[-0.0112, -0.0112, -0.0112,  ..., -0.0112, -0.0112, -0.0112],
2024-09-12 16:42:59 | INFO | stdout |           [-0.0112, -0.0112, -0.0112,  ..., -0.0112, -0.0112, -0.0112],
2024-09-12 16:42:59 | INFO | stdout |           [-0.0112, -0.0112, -0.0112,  ..., -0.0112, -0.0112, -0.0112],
2024-09-12 16:42:59 | INFO | stdout |           ...,
2024-09-12 16:42:59 | INFO | stdout |           [-0.0112, -0.0112, -0.0112,  ..., -0.0112, -0.0112, -0.0112],
2024-09-12 16:42:59 | INFO | stdout |           [-0.0112, -0.0112, -0.0112,  ..., -0.0112, -0.0112, -0.0112],
2024-09-12 16:42:59 | INFO | stdout |           [-0.0112, -0.0112, -0.0112,  ..., -0.0112, -0.0112, -0.0112]],
2024-09-12 16:42:59 | INFO | stdout |
2024-09-12 16:42:59 | INFO | stdout |          [[-0.0013, -0.0013, -0.0013,  ..., -0.0013, -0.0013, -0.0013],
2024-09-12 16:42:59 | INFO | stdout |           [-0.0013, -0.0013, -0.0013,  ..., -0.0013, -0.0013, -0.0013],
2024-09-12 16:42:59 | INFO | stdout |           [-0.0013, -0.0013, -0.0013,  ..., -0.0013, -0.0013, -0.0013],
2024-09-12 16:42:59 | INFO | stdout |           ...,
2024-09-12 16:42:59 | INFO | stdout |           [-0.0013, -0.0013, -0.0013,  ..., -0.0013, -0.0013, -0.0013],
2024-09-12 16:42:59 | INFO | stdout |           [-0.0013, -0.0013, -0.0013,  ..., -0.0013, -0.0013, -0.0013],
2024-09-12 16:42:59 | INFO | stdout |           [-0.0013, -0.0013, -0.0013,  ..., -0.0013, -0.0013, -0.0013]]]],
2024-09-12 16:42:59 | INFO | stdout |        device='cuda:0', dtype=torch.float16), 'modal_list': ['image']}

2024-09-12 16:42:59 | ERROR | stderr | Exception in thread Thread-3:
2024-09-12 16:42:59 | ERROR | stderr | Traceback (most recent call last):
2024-09-12 16:42:59 | ERROR | stderr |   File "/root/miniconda3/envs/vllama/lib/python3.9/threading.py", line 980, in _bootstrap_inner
2024-09-12 16:42:59 | ERROR | stderr |     self.run()
2024-09-12 16:42:59 | ERROR | stderr |   File "/root/miniconda3/envs/vllama/lib/python3.9/threading.py", line 917, in run
2024-09-12 16:42:59 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-09-12 16:42:59 | ERROR | stderr |   File "/root/miniconda3/envs/vllama/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-09-12 16:42:59 | ERROR | stderr |     return func(*args, **kwargs)
2024-09-12 16:42:59 | ERROR | stderr |   File "/chenjiahui/VideoLLaMA2/videollama2/model/videollama2_mistral.py", line 148, in generate
2024-09-12 16:42:59 | ERROR | stderr |     return super().generate(
2024-09-12 16:42:59 | ERROR | stderr |   File "/root/miniconda3/envs/vllama/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-09-12 16:42:59 | ERROR | stderr |     return func(*args, **kwargs)
2024-09-12 16:42:59 | ERROR | stderr |   File "/root/miniconda3/envs/vllama/lib/python3.9/site-packages/transformers/generation/utils.py", line 1307, in generate
2024-09-12 16:42:59 | ERROR | stderr |     self._validate_model_kwargs(model_kwargs.copy())
2024-09-12 16:42:59 | ERROR | stderr |   File "/root/miniconda3/envs/vllama/lib/python3.9/site-packages/transformers/generation/utils.py", line 1122, in _validate_model_kwargs
2024-09-12 16:42:59 | ERROR | stderr |     raise ValueError(
2024-09-12 16:42:59 | ERROR | stderr | ValueError: The following `model_kwargs` are not used by the model: ['images_or_videos', 'modal_list'] (note: typos in the generate arguments will also show up in this list)
```

Is there any way to fix this?

**Comment by clownrat6** [comment]
Could you please provide the executed command for debugging?

**Comment by LiangMeng89** [comment]
Hello,I'm a phD student from ZJU, I also use videollama2 to do my own research,we create a WeChat group to discuss some issues of videollama2 and help each other,could you join us? Please contact me: WeChat number == LiangMeng19357260600, phone number == +86 19357260600,e-mail == liangmeng89@zju.edu.cn.
